name: cpc_torch
channels:
  - anaconda
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - datasets=2.11.0
  - huggingface_hub=0.14.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - numpy=1.23.4
  - numpy-base=1.23.4
  - pandas=1.5.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - pip:
      - charset-normalizer==2.1.1
      - tqdm==4.64.1
      - urllib3==1.26.13
