name: cpc_torch
channels:
  - anaconda
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - datasets=2.11.0
  - huggingface_hub=0.14.1
  - matplotlib
  - numpy
  - pandas
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - scikit-learn
  - scipy
  - pip
  - pip:
      - charset-normalizer==2.1.1
      - tqdm
      - urllib3==1.26.13
